# Engine command goal
string command
string CALIBRATION_START=start
string CALIBRATION_STOP=stop

---
# result
bool result
string status_id
# possible values for statusId are:
string SUCCESS=Success
string STOPPED=Stopped
string GENERIC_FAILURE=calibration_failure
string INCOMPLETE=incomplete
string GRIPPER_ON=cannot_calibrate_with_gripper
string TORQUES_EXCEEDED_THRESHOLD=torques_exceeded_threshold
string PLANNER_FAILURE=planner_failure


---
# feedback
string current_state
uint32 number_of_poses
uint32 current_pose_number
